### ISSUE TITLE
CalDAV integration planned?

### ISSUE THREAD

**Issue by blu-IT** [staxDB/humhub-modules-external-calendar#3]
Hello,

is there any CalDAV integration planned?

I'd love to see support for integration of [nextcloud](https://nextcloud.com/) calendar into HumHub (and vice versa)!

Kind regards

**Comment by staxDB** [comment]
currently not, the module was developed for a company, not for the general public. 
However, I thought that it might also make sense for some people and therefore I published it.

**Comment by blu-IT** [comment]
OK, that's a pity. Unfortunately I am not a developer, can only support with translations...
