### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by blu-IT** [staxDB/humhub-modules-external-calendar#4]
Hi,

I have prepared an italian translation of the files. How to commit? Can't push...

Thanks!

Regards

**Comment by staxDB** [comment]
guess you should look at these [instructions](https://github.com/MarcDiethelm/contributing/blob/master/README.md)

**Comment by blu-IT** [comment]
OK, thanks! Created a pull request now.

https://github.com/staxDB/external_calendar/pull/5
