### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by 001101** [staxDB/humhub-modules-external-calendar#6]
hello,

really great new module, thanks alot!

but it would be nicer if you can use the official default naming for the repo, with humhub-modules in front, like this:

humhub-modules-external-calendar

as you can see here the official modules:

https://github.com/humhub/humhub-modules-calendar
https://github.com/humhub/humhub-modules-custom-pages
https://github.com/humhub/humhub-modules-mail

it is easier to find in searches and better categorized. 

greets

**Comment by staxDB** [comment]
Is there a way to rename a project in Github without any problems?

**Comment by 001101** [comment]
sure, just go to the repo under settings and change the name :)

**Comment by staxDB** [comment]
Renamed
