### ISSUE TITLE
Class 'Carbon\Carbon' not found

### ISSUE THREAD

**Issue by levikoenig** [staxDB/humhub-modules-external-calendar#7]
Installed this module into HumHub. Was able activate it successfully. But when I add an iCal link from Google Calendar and save, I get error screen saying 'Class 'Carbon\Carbon' not found'. I don't know very much about this stuff but I thought I would share if for some reason it was helpful :)

Exception
Error
Class 'Carbon\Carbon' not found
1. in /var/www/html/humhub_source/protected/modules/humhub-modules-external-calendar/vendors/johngrogg/ics-parser/src/ICal/ICal.php at line 2107
2098209921002101210221032104210521062107210821092110211121122113211421152116                if ($key === 'TZID') {
                    $currentTimeZone = $subArray[$key];
                } elseif (is_numeric($key)) {
                    $icalDate = $subArray[$key];
 
                    if (substr($icalDate, -1) === 'Z') {
                        $currentTimeZone = self::TIME_ZONE_UTC;
                    }
 
                    $output[] = new Carbon($icalDate, $currentTimeZone);
 
                    if ($key === $finalKey) {
                        // Reset to default
                        $currentTimeZone = $this->defaultTimeZone;
                    }
                }
            }
        }
 
2. in /var/www/html/humhub_source/protected/modules/humhub-modules-external-calendar/vendors/johngrogg/ics-parser/src/ICal/ICal.php at line 931 – ICal\ICal::parseExdates(['DTSTART_array' => [['TZID' => 'America/Edmonton'], '20160317T080000', 1458223200, 'TZID=America/Edmonton:20160317T0...'], 'DTSTART' => '20160317T080000', 'DTEND_array' => [['TZID' => 'America/Edmonton'], '20160317T170000', 1458255600, 'TZID=America/Edmonton:20160317T1...'], 'DTEND' => '20160317T170000', ...])
925926927928929930931932933934935936937 
                $untilDefault = date_create('now');
                $untilDefault->modify($this->defaultSpan . ' year');
                $untilDefault->setTime(23, 59, 59); // End of the day
 
                // Compute EXDATEs
                $exdates = $this->parseExdates($anEvent);
 
                if (isset($rrules['UNTIL'])) {
                    // Get Until
                    $until = strtotime($rrules['UNTIL']);
                } elseif (isset($rrules['COUNT'])) {
                    $countOrig = (is_numeric($rrules['COUNT']) && $rrules['COUNT'] > 1) ? $rrules['COUNT'] : 0;
3. in /var/www/html/humhub_source/protected/modules/humhub-modules-external-calendar/vendors/johngrogg/ics-parser/src/ICal/ICal.php at line 402 – ICal\ICal::processRecurrences()
396397398399400401402403404405406407408                }
            }
 
            $this->processEvents();
 
            if (!$this->skipRecurrence) {
                $this->processRecurrences();
            }
 
            $this->processDateConversions();
        }
    }
 
4. in /var/www/html/humhub_source/protected/modules/humhub-modules-external-calendar/vendors/johngrogg/ics-parser/src/ICal/ICal.php at line 245 – ICal\ICal::initLines(['BEGIN:VCALENDAR', 'PRODID:-//Google Inc//Google Cal...', 'VERSION:2.0', 'CALSCALE:GREGORIAN', ...])
239240241242243244245246247248249250251                if ($this->isFileOrUrl($file)) {
                    $lines = $this->fileOrUrl($file);
                } else {
                    $lines = is_array($file) ? $file : array($file);
                }
 
                $this->initLines($lines);
            }
        }
    }
 
    /**
     * Initialises lines from a string
5. in /var/www/html/humhub_source/protected/modules/humhub-modules-external-calendar/models/ExternalCalendar.php at line 167 – ICal\ICal::__construct(['https://calendar.google.com/cale...'], ['defaultTimeZone' => 'America/Edmonton'])
161162163164165166167168169170171172173     * @param array $params parameters
     */
    public function validateURL($attribute, $params)
    {
        try {
            new ICal($this->url, array(
                'defaultTimeZone' => Yii::$app->timeZone,
            ));
        } catch (\Exception $e) {
            $this->addError($attribute, Yii::t('ExternalCalendarModule.sync_result', "No valid ical url! Try an url with http / https."));
        }
    }
 
6. humhub\modules\external_calendar\models\ExternalCalendar::validateURL('url', null, yii\validators\InlineValidator)
7. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/validators/InlineValidator.php at line 72 – call_user_func([humhub\modules\external_calendar\models\ExternalCalendar, 'validateURL'], 'url', null, yii\validators\InlineValidator)
8. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/validators/Validator.php at line 266 – yii\validators\InlineValidator::validateAttribute(humhub\modules\external_calendar\models\ExternalCalendar, 'url')
9. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/base/Model.php at line 358 – yii\validators\Validator::validateAttributes(humhub\modules\external_calendar\models\ExternalCalendar, ['url'])
10. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/db/ActiveRecord.php at line 564 – yii\base\Model::validate(['title', 'url', 'time_zone', 'color', ...])
11. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 645 – yii\db\ActiveRecord::update(true, null)
12. in /var/www/html/humhub_source/protected/modules/humhub-modules-external-calendar/controllers/CalendarController.php at line 184 – yii\db\BaseActiveRecord::save()
178179180181182183184185186187188189190        if (!$this->canManageCalendar()) {
            throw new HttpException(403, Yii::t('ExternalCalendarModule.permissions', 'You are not allowed to manage External Calendar!'));
        }
 
        $model = $this->findModel($id);
 
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $ical = SyncUtils::createICal($model->url);
            if ($ical) {
                // add info to CalendarModel
                $model->addAttributes($ical);
                $model->save();
            } else {
13. humhub\modules\external_calendar\controllers\CalendarController::actionUpdate('3')
14. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\modules\external_calendar\controllers\CalendarController, 'actionUpdate'], ['3'])
15. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams(['r' => 'external_calendar/calendar/updat...', 'id' => '3', 'sguid' => 'ec3314fb-c619-48db-9c0b-48fb0305...', '_pjax' => '#layout-content', ...])
16. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('update', ['r' => 'external_calendar/calendar/updat...', 'id' => '3', 'sguid' => 'ec3314fb-c619-48db-9c0b-48fb0305...', '_pjax' => '#layout-content', ...])
17. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('external_calendar/calendar/updat...', ['r' => 'external_calendar/calendar/updat...', 'id' => '3', 'sguid' => 'ec3314fb-c619-48db-9c0b-48fb0305...', '_pjax' => '#layout-content', ...])
18. in /var/www/html/humhub_source/protected/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(humhub\components\Request)
19. in /var/www/html/humhub_source/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 Yii Framework
2018-03-29, 18:03:19

Apache/2.4.25 (Debian)

Yii Framework/2.0.12

Hidden Gallery
‹ › ×
×
Add image/file
 Upload

Close
×
Add link
Title  
Title of your link
Target  
Enter a url (e.g. http://example.com)
 Close  Add link

**Comment by lweddewer** [comment]
I have seen the same failure with one google calendar.
But with two others calendars it works fine. :confused: 

Comparing the ical-files I've seen the the mailfunction calendar have the following additional entries:

```ical
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
```


Maybe this helps.

**Comment by staxDB** [comment]
First of all: Try the latest Release: https://github.com/staxDB/humhub-modules-external-calendar/releases/tag/v0.1.5

If that doesn't work, try this release: https://github.com/staxDB/humhub-modules-external-calendar/releases/tag/v0.1.4

If there's still an error, maybe the issue is because of the third-party code I use for this module:
https://github.com/u01jmg3/ics-parser

**Comment by staxDB** [comment]
Is this issue solved?

**Comment by levikoenig** [comment]
Yes! I tried installing the module again today and there were no errors. I successfully hooked up a Google calendar using the private ical link. Thanks!
